name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: andersonr
          url: https://git.infraops.info/andersonr/PeerTube-Fork.git
          # Personal access token from gitlab.com 
          token: glpat-VnQqreUnWgvZ1WQYKqVp
